Add validation to check if textfile is empty
jzohrab/lute-v3 pull request #337
Opened 2024-03-14 14:23 UTC by Jayanth-Parthsarathy

# Check if file is empty before uploading

Fixes #335 

- [x] Add validation to check if file uploaded is empty
## Screenshots

![image](https://github.com/jzohrab/lute-v3/assets/86654557/2abbf1dd-92bd-41d5-b63c-7724284907d6)

2024-03-14 14:25 UTC, Jayanth-Parthsarathy commented
Hey @jzohrab. Please have a look at this and let me know if there are any changes :)

2024-03-14 14:40 UTC, jzohrab requested changes
Hi @Jayanth-Parthsarathy - I think this will miss some cases.  If you take a look at the `/new` route in routes.py, you'll see the line:

```
b.text = _get_file_content(form.textfile.data)
```

So that gets content from epubs, vtt, etc files, after those have been parsed by the appropriate libraries.

Probably the easiest thing would just be to add a check for empty book text (after stripping the string) just before adding the book to the repo, and if it's blank, just flash an error message or something, and don't save the book.

2024-03-15 03:32 UTC, Jayanth-Parthsarathy commented
@jzohrab. Please take a look at it now and let me know if anything needs to be changed

2024-03-17 14:04 UTC, jzohrab commented
Hi @Jayanth-Parthsarathy - I'm holding off on this for now due to issue #99 and its PR #347 , b/c that PR has been occupying my brain, as mentioned in the discord developers channel thread :-)

I see what you've done and think it might be done a bit differently.  I don't really like the way that the current code does the populate_obj and then does some extra stuff ... it's a bit messy, and I'd like to try to make it cleaner later.  Having the multiple nested ifs and returns just feels chaotic, you know?  Maybe there's a better way, but I don't want you to try to sort it out, because I've kind of made a mess with it.

2024-03-22 21:38 UTC, jzohrab commented
Hi again @Jayanth-Parthsarathy ,

I restructured some things so now the code in the route just looks like this:

```
    if form.validate_on_submit():
        try:
            form.populate_obj(b)
            book = repo.add(b)
            repo.commit()
            return redirect(f"/read/{book.id}/page/1", 302)
        except service.BookImportException as e:
            flash(e.message, "notice")
```

The populate_obj call uses the service to load the data, and the service itself does a check for the empty file, and throws a `BookImportException(f"{filefielddata.filename} is empty.")` if needed.

The original code I had was bad, and needed to be fixed.  Routes should generally be simple, if possible :-).  With the revision, this PR isn't needed.  Thanks for the submission though!

2024-03-22 21:38 UTC, closed without merging

2024-03-25 09:53 UTC, jzohrab commented
Launched in 3.3.0.